<a href="https://colab.research.google.com/github/Keerthiga-I/PYTHON-CODE/blob/PYTHON-LEVELS/pandas_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = [{'A':1,'B':2*i} for i in range(3)]
data

[{'A': 1, 'B': 0}, {'A': 1, 'B': 2}, {'A': 1, 'B': 4}]

In [ ]:
df = pd.DataFrame(data)
df

   A  B
0  1  0
1  1  2
2  1  4

In [ ]:
df = pd.DataFrame(data,index=['X','Y','Z'])
df

   A  B
X  1  0
Y  1  2
Z  1  4

In [ ]:
df.columns

Index(['A', 'B'], dtype='object')

In [ ]:
df.columns = ['A','B']
df

   A  B
0  1  0
1  1  2
2  1  4

In [ ]:
df.index = ['m','n','o']
df

   A  B
m  1  0
n  1  2
o  1  4